import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<body>
  <div className="min-h-screen flex flex-col">

    {/* Navigation */}
    <nav className="bg-black text-white px-6 py-4 flex justify-between">
      <div className="font-bold text-lg">
        Supplier Gateway
      </div>
      <div className="space-x-6">
        <a href="/" className="hover:underline">Home</a>
        <a href="/search" className="hover:underline">Search</a>
        <a href="/suppliers" className="hover:underline">Suppliers</a>
      </div>
    </nav>

    {/* Page Content */}
    <main className="flex-1 p-8">
      {children}
    </main>

  </div>
</body>
    </html>
  );
}
